language: python
os: linux
dist: xenial

# ======================== LINUX ========================
python:
  - 3.7.9
  - 3.8

branches:
  only:
  - master

jobs:
    include:
    # ======================== WINDOWS ========================
    - name: "Python 3.8.6 on Windows"
      os: windows        # Windows 10.0.17134 N/A Build 17134
      language: shell    # 'language: python' is an error on Travis CI Windows
      env: PATH=/c/tools/miniconda3/:/c/tools/miniconda3/Scripts:/c/tools/miniconda3//Library/bin:$PATH
      before_install:
        # ---------------------------------------------------------------------
        # Set up path variables for Chocolatey installation of miniconda
        - export CONDA_PATH=/c/Tools/miniconda3
        - export CONDA_BIN=$CONDA_PATH/Library/bin:$CONDA_PATH/condabin
        - export CONDA_SCRIPTS=$CONDA_PATH/Scripts
        - export PATH=$CONDA_PATH:$CONDA_BIN:$CONDA_SCRIPTS:$PATH
        # Install Anaconda and configure conda
        - choco install miniconda3 --params="'/JustMe /AddToPath'"
        - echo $PATH
        - source "$CONDA_PATH/etc/profile.d/conda.sh"
        - hash -r
        - conda config --set always_yes yes --set changeps1 no
        - conda config --set pip_interop_enabled True
        - conda update -q conda
        - conda info -a
      install:
        # ---------------------------------------------------------------------
        # Create and activate the environment
        - conda env create -n sira_env -f ./installation/environment.yml
        - source "$CONDA_PATH/Scripts/activate"
        - conda activate sira_env
        - python -m pip install --upgrade pip
        - conda --version ; python --version ; pip --version
        - conda list
        # ---------------------------------------------------------------------

install:
  - sudo apt-get install -y --no-install-recommends apt-utils
  - sudo apt-get install -y  $(awk '{print $1}' ./installation/packagelist_linux.txt)
  - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O /tmp/miniconda.sh
  - bash /tmp/miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - export PATH="$HOME/miniconda/bin:$PATH"
  - export PYTHONPATH="$PYTHONPATH:$(pwd)"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --set pip_interop_enabled True
  - conda update -q conda
  - conda info -a
  - conda create -q -n sira_env python=$TRAVIS_PYTHON_VERSION
  - eval "$(conda shell.bash hook)"
  - conda activate sira_env
  - conda install libtiff libpng
  - conda list
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install -r ./installation/requirements.txt

script:
  - if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then
      python3 -m pytest;
    elif [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
      python -m pytest;
    fi;

after_success:
  - codecov
  - bash <(curl -s https://codecov.io/bash)
