name: sifra_env
channels:
    - anaconda
    - marufr
dependencies:
    - anaconda-client=1.1.2=py27_0
    - appnope=0.1.0=py27_0
    - clyent=1.0.0=py27_0
    - colorama=0.3.3=py27_0
    - cycler=0.9.0=py27_0
    - decorator=4.0.4=py27_0
    - freetype=2.5.5=0
    - ipython=4.0.0=py27_1
    - ipython_genutils=0.1.0=py27_0
    - jbig=2.1=0
    - jpeg=8d=1
    - libpng=1.6.17=0
    - libtiff=4.0.6=1
    - libxml2
    - matplotlib=1.5.1=np110py27_0
    - mkl=11.3.1=0
    - networkx=1.10=py27_0
    - numexpr=2.5=np110py27_0
    - numpy=1.10.4=py27_0
    - openssl=1.0.2d=0
    - pandas=0.17.1=np110py27_0
    - path.py=8.1.2=py27_0
    - pexpect=3.3=py27_0
    - pickleshare=0.5=py27_0
    - pillow=3.0.0=py27_1
    - pip=8.0.2=py27_0
    - ptyprocess=0.5=py27_0
    - pydot=1.0.28=py27_0
    - pygraphviz=1.3.1=py27_0
    - pyqt=4.11.4=py27_1
    - python=2.7.11=0
    - python-dateutil=2.4.2=py27_0
    - python.app=1.2=py27_4
    - pytz=2015.7=py27_0
    - pyyaml=3.11=py27_1
    - qt=4.8.7=1
    - readline=6.2=2
    - requests=2.8.1=py27_0
    - scikit-learn=0.17=np110py27_1
    - scipy=0.17.0=np110py27_0
    - seaborn=0.7.0=py27_0
    - setuptools=20.1.1=py27_0
    - simplegeneric=0.8.1=py27_0
    - sip=4.16.9=py27_0
    - six=1.10.0=py27_0
    - sqlite=3.9.2=0
    - tk=8.5.18=0
    - traitlets=4.0.0=py27_0
    - wheel=0.29.0=py27_0
    - xlrd=0.9.4=py27_0
    - xz=5.0.5=0
    - yaml=0.1.6=0
    - zlib=1.2.8=0
- pip:
    - actdiag==0.5.1
    - alabaster==0.7.7
    - babel==2.2.0
    - blockdiag==1.5.3
    - brewer2mpl==1.4.1
    - docutils==0.12
    - funcparserlib==0.3.6
    - ipython-genutils==0.1.0
    - jinja2==2.8
    - lmfit==0.9.2
    - markupsafe==0.23
    - nwdiag==1.0.0
    - parmap==1.5.1
    - pybtex==0.19
    - pybtex-docutils==0.2.1
    - pygments==2.1
    - python-igraph==0.7.1.post6
    - seqdiag==0.9.0
    - snowballstemmer==1.2.1
    - sphinx==1.3.6
    - sphinx-rtd-theme==0.1.9
    - sphinxcontrib-actdiag==0.6.0
    - sphinxcontrib-bibtex==0.3.3
    - sphinxcontrib-blockdiag==1.5.5
    - sphinxcontrib-nwdiag==0.7.0
    - sphinxcontrib-seqdiag==0.6.0
    - webcolors==1.5

