name: sira_env
channels:
    - conda-forge
    - default
dependencies:
    - pip=21.3.1
    - awscli=1.21.9
    - brewer2mpl=1.4.1
    - codecov=2.1.11
    - colorama=0.4.3
    - configparser=5.0.2
    - coverage=6.1.1
    - docutils=0.15.2
    - freetype=2.10.4
    - graphviz=2.49.1
    - ipython=7.32.0
    - jupyterlab=3.2.1
    - imagecodecs=2021.8.26
    - imageio=2.9.0
    - imagesize=1.2.0
    - latexcodec=2.0.1
    - lmfit=1.0.3
    - matplotlib=3.4.3
    - netcdf4=1.5.8
    - networkx=2.6.3
    - notebook=6.4.5
    - numpy=1.22.2
    - openpyxl=3.0.9
    - pandas=1.3.4
    - parmap=1.5.3
    - pillow=8.3.2
    - pycairo=1.20.1
    - pycparser=2.20
    - pygments=2.10.0
    - pylint=2.11.1
    - pytest=6.2.5
    - pytest-cov=3.0.0
    - python-graphviz=0.17
    - python-igraph=0.9.8
    - python-libarchive-c
    - requests=2.26.0
    - s3transfer=0.5.0
    - scikit-image=0.18.3
    - scikit-learn=1.0.1
    - scipy=1.7.1
    - seaborn=0.11.2
    - sqlalchemy=1.4.26
    - xlrd=2.0.1
    - xorg-libxrender=0.9.10
    - xorg-libxpm=3.5.13
    - pip:
        - actdiag==2.0.0
        - alabaster==0.7.12
        - blockdiag==2.0.1
        - pybtex==0.22.2
        - pybtex-docutils==0.2.2
        - seqdiag==2.0.0
        - sphinx==3.2.1
        - sphinx-rtd-theme==0.5.0
        - sphinxcontrib-actdiag==2.0.0
        - sphinxcontrib-bibtex==1.0.0
        - sphinxcontrib-blockdiag==2.0.0
        - sphinxcontrib-jsmath==1.0.1
        - sphinxcontrib-seqdiag==2.0.0
        - sphinxcontrib-websupport==1.2.4
