name: Build and Test on Windows

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:

  build-windows:
    runs-on: "windows-latest"
    strategy:
      matrix:
        python-version: ['3.8', '3.9']

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Build env with conda
        run: |
          conda create -n sira_env python=${{ matrix.python-version }}
          conda activate sira_env
          conda env update --file ./installation/environment.yml

      - name: Install dependencies
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          auto-activate-base: false
          activate-environment: sira_env
          python-version: 3.8
          environment-file: ./installation/environment.yml

      - name: List conda packages
        shell: bash -l {0}
        run: |
          conda info
          conda list

      - name: Run pytest
        shell: bash -l {0}
        run: pytest

      - name: Upload Coverage to codecov
        uses: codecov/codecov-action@v2
