name: Build and Test on Windows

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:

  build-windows:
    runs-on: "windows-latest"
    strategy:
      matrix:
        python-version: ['3.8', '3.9']

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies with conda
        shell: powershell
        run: |
          C:\Miniconda\condabin\conda.bat init powershell
          C:\Miniconda\condabin\conda.bat create -n test_env python=${{ matrix.python-version }}
          C:\Miniconda\condabin\conda.bat activate test_env
          C:\Miniconda\condabin\conda.bat env update --file ./installation/environment.yml
          C:\Miniconda\condabin\conda.bat info
          C:\Miniconda\condabin\conda.bat list

      - name: Run pytest
        shell: powershell
        run: |
          C:\Miniconda\condabin\conda.bat activate test_env
          pytest

      - name: Upload Coverage to codecov
        uses: codecov/codecov-action@v2
