name: CI on WIN

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:

  build-windows:
    runs-on: "windows-latest"

    strategy:
      matrix:
        python-version: ['3.11']

    steps:

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: ./installation/sira_env.yml
          environment-name: sira_env
          create-args: >-
            python=${{ matrix.python-version }}
          init-shell: powershell
          cache-environment: true

      - name: Install uv and requirements
        shell: powershell
        run: |
          micromamba activate sira_env
          micromamba install uv
          uv pip install -r ./installation/sira_req.txt

      - name: Check environment
        shell: powershell
        run: |
          micromamba info
          micromamba list

      - name: Run pytest
        shell: powershell
        run: |
          micromamba activate sira_env
          python -m pytest

      - name: Upload Coverage to codecov
        uses: codecov/codecov-action@v2
