name: CI on WIN

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:

  build-windows:
    runs-on: "windows-latest"

    env:
      CONDA: C:\Miniconda\condabin\conda.bat

    strategy:
      matrix:
        python-version: ['3.11']

    steps:

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies with conda
        shell: powershell
        run: |
          ${{ env.CONDA }} init powershell
          ${{ env.CONDA }} create -n base python=${{ matrix.python-version }}
          ${{ env.CONDA }} env update -f ./installation/sira_env.yml -n base
          ${{ env.CONDA }} activate base
          ${{ env.CONDA }} install uv
          $uv pip install -r ./installation/sira_req.txt

      - name: Check environment
        shell: powershell
        run: |
          ${{ env.CONDA }} info
          ${{ env.CONDA }} list

      - name: Run pytest
        shell: powershell
        run: |
          ${{ env.CONDA }} activate base
          python -m pytest

      - name: Upload Coverage to codecov
        uses: codecov/codecov-action@v2
