name: SIRA Build and Test usng Anaconda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        $CONDA/bin/conda install libtiff libpng
        $CONDA/bin/conda list
        pip install -U pip
        pip install -r ./installation/requirements.txt
    - name: Install coverage dependency
      run: pip install --upgrade coverage[toml]
    - name: Run Test Suite with pytest
      run: |
        pip install pytest
        pytest
