name: Build and Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:

  build-linux:
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        python-version: ['3.8', '3.9']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies for linux
        run: |
          sudo apt-get install graphviz graphviz-dev
          $CONDA/bin/conda install libtiff libpng
          pip install -U pip
          pip install -r ./installation/requirements.txt

  build-windows:
    runs-on: "windows-latest"
    strategy:
      matrix:
        python-version: ['3.8', '3.9']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies for windows
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          auto-activate-base: false
          activate-environment: sira_env
          python-version: ${{ matrix.python-version }}
          environment-file: ./installation/environment.yml

      - name: List conda packages
        shell: bash -l {0}
        run: |
          conda info
          conda list

      - name: Run pytest
        shell: bash -l {0}
        run: pytest

      - name: Upload Coverage to codecov
        uses: codecov/codecov-action@v2
