name: Build and Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ['3.8', '3.9']

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies for ${{ matrix.os }}
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          $CONDA/bin/conda install libtiff libpng
          sudo apt-get install graphviz graphviz-dev
          pip install -U pip
          pip install -r ./installation/requirements.txt

      - name: Install dependencies for ${{ matrix.os }}
        if: ${{ matrix.os == 'windows-latest' }}
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: sira_env
          environment-file: installation/environment.yml
          python-version: ${{ matrix.python-version }}
          auto-activate-base: false
        shell: bash -l {0}
        run: |
          conda info
          conda list

      - name: Run pytest
        run: pytest

      - name: Upload Coverage to covercov
        uses: codecov/codecov-action@v2
